version: '3'

services:
  country-service:
    image: app-service
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/app-service
    ports:
      - "8280:8280"
      
  kibana:
    image: kibana:6.5.2
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601
  logstash: 
    hostname: logstash 
    image: docker-logs-elk/logstash:1.0.0
    build:
      context: logstash
      dockerfile: Dockerfile
    ports:
      - 5044:5044
    environment:
      LOG_LEVEL: error
    links:
      - elasticsearch
  elasticsearch:
    hostname: elasticsearch
    image: docker-logs-elk/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  logspout:
    image: gliderlabs/logspout:v3.2.4
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
        - "ROUTE_URIS=syslog+tcp://logstash:5000"
    logging:
      driver: json-file

  curator: 
    image: bobrik/curator:5.4.0 
    volumes: 
      - ./curator/crontab:/var/spool/cron/crontabs/root 
      - ./curator/curator.yml:/home/saif.rehman/.curator/curator.yml 
      - ./curator/curator_action.yml:/home/saif.rehman/.curator/curator_action.yml 
      - /etc/localtime:/etc/localtime:ro
    user: root 
    entrypoint: ""
    command: crond -l 0 -f
    logging: 
      driver: json-file 
